### ISSUE TITLE
Allow Small Cells Again

### ISSUE THREAD

**Issue by say25** [cuappdev/eatery-ios#126]
Small Cells (½ width on iPhone, ⅓ width on iPad) makes it a lot easier to scroll through longer lists of eateries. On current iPad version you can see a large number of cells, on current version you can only see 3. with a screen that large we are wasting much of the screen real estate. I understand that iPad is a very small percent of our user base but its bad practice to take away current functionality without just cause.

Proposed Solution:
With Guide moving to a tab, replace guide button with cell size toggle button. Some iPhone users probably prefer existing cell size to large cells. Especially on larger devices 4.7/5.5 inch devices (6/6+)

**Comment by dennisfedorko** [comment]
Were going with full width on iPhone and iPad for cells

**Comment by say25** [comment]
discussed with @dennisfedorko and @acheng96 and thought this could be done as future enhancement.
Put change cell button in top right after guide moves to tab bar. if not use top left button spot.
![grid](https://cloud.githubusercontent.com/assets/7467062/20782624/0e3c1724-b753-11e6-92ae-1583f9f79434.png)
![table](https://cloud.githubusercontent.com/assets/7467062/20782625/0e51da5a-b753-11e6-870a-19f817c80800.png)

**Comment by dantheli** [comment]
This has been implemented for certain size classes since version 2.2.0
