### ISSUE TITLE
Shouldn't be able to click both North and West

### ISSUE THREAD

**Issue by anniexcheng** [cuappdev/eatery-ios#129]
i.e. Nearest and (North or West)

OR for locations
OR for swipes/BRB

**Comment by say25** [comment]
Could this be a feature? Basically **North** and **West** selected and Central not would mean show me all eateries that are on north or west?

**Comment by dantheli** [comment]
I've been silently mulling about that feature and want to know what everyone thinks would be best

**Comment by dennisfedorko** [comment]
We discussed this during design crit today. If you tap North and West, it should display both North and West. So for places it should be an OR operation. If you tap filter by BRB or Swipes, only one of these should be selected at a time. Nearest should be combinable with all other options.

Currently all the filters are AND operations, but we need to consider the behavior carefully for all combos.

**Comment by dantheli** [comment]
Ok I'll do it tomorrow
