### ISSUE TITLE
Peek and Pop into menu view controller messes up scroll views

### ISSUE THREAD

**Issue by dantheli** [cuappdev/eatery-ios#133]

**Comment by dennisfedorko** [comment]
We should delete peek + pop as it provides exactly the same functionality as just tapping the cell

**Comment by say25** [comment]
Peek + Pop are used to quickly preview. Its definitely not MVP for 2.0 IMHO maybe comment out and add to 2.X?

**Comment by say25** [comment]
Peek + Pop are used to quickly preview. Its definitely not MVP for 2.0 IMHO maybe comment out and add to 2.X? also i don't personally see the bug. 
<img src=https://cloud.githubusercontent.com/assets/7467062/20785326/3af1b884-b765-11e6-844f-87530d3b2d38.PNG width=200 />

**Comment by dantheli** [comment]
So I jumped the gun on this one. The bug is on my branch. Pop and then scroll to the bottom.

**Comment by dantheli** [comment]
No longer a major issue since SnapKit refactor
