### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by dennisfedorko** [cuappdev/eatery-ios#141]
Add support for push notifications to spread updates to users about our other apps or in case of a bug send a warning to users

**Comment by say25** [comment]
^Is this a "please update to version X.X.X for best performance" message? I think telling a user to download our other apps is against an apple policy by we could have a [link](https://itunes.apple.com/us/developer/walker-white/id1089672961) to our apps in the about section.

**Comment by dennisfedorko** [comment]
content of push is independent of this feature, we need support for pushing any arbitrary message.
