### ISSUE TITLE
Meal swips shows as 0?

### ISSUE THREAD

**Issue by jk2227** [cuappdev/eatery-ios#142]
Living on West Camps I am on the House Meal Plans but it shows my Meal Swipes as 0

**Comment by say25** [comment]
I would assume BRBConnectionHandler.swift line 197 is the root cause with unlimited swipes not getting parsed properly.

**Comment by say25** [comment]
I would believe this is no longer a bug after 92d5e0f. Can we verify?

**Comment by dantheli** [comment]
Correct, bug fix was just merged into master
