### ISSUE TITLE
House dinners not displaying properly

### ISSUE THREAD

**Issue by jk2227** [cuappdev/eatery-ios#144]
Why is this showing a menu? It's supposed to be house dinner O:    

![image](https://cloud.githubusercontent.com/assets/8561804/24222751/885df2c4-0f29-11e7-8b2f-7dc711eb4a22.png)

**Comment by say25** [comment]
It should show whatever data Cornell Dining provides. Seems like its showing the correct data. https://now.dining.cornell.edu/eatery/Keeton-House-Dining 
<img width="661" alt="screen shot 2017-03-22 at 9 18 31 pm" src="https://cloud.githubusercontent.com/assets/7467062/24228955/1f13affe-0f45-11e7-8021-cf72c5f3553d.png">

**Comment by jk2227** [comment]
I see; given that Wednesdays are house dinner for West campus, however, would it be better to have a manual check on whether it's Wednesday or not for dining halls on West campus for dinners?

**Comment by say25** [comment]
I would disagree. Ideally that was what was served for house dinner. Having a Wednesday check and puts a little banner up reminding users it could be house dinner could be a good improvement though
