### ISSUE TITLE
House Dinner System

### ISSUE THREAD

**Issue by dantheli** [cuappdev/eatery-ios#159]
Every house on West Campus knows what house dinner is going to be ahead of time
Perhaps we can convince them to input their menus on a custom made system by us to combine with the eateries data

**Comment by say25** [comment]
Wouldn’t it make sense to have them input it to the Cornell Dining API that we already consume so it also goes to CUDining for free

**Comment by dantheli** [comment]
Good point, we should just talk to them about why there's friction to input it
