### ISSUE TITLE
Firebase Analytics Events

### ISSUE THREAD

**Issue by chalo2000** [cuappdev/eatery-ios#214]
We want to get the number of presses done on
1) Collegetown button on pill
2) Campus button on pill
3) Lookahead tab button
4) BRB Account tab button
5) BRB Login Button
6) Any Campus filter button
7) Any Collegetown filter button

**Comment by kevinchan159** [comment]
should try to use `AppDevAnalytics` pod for this!

**Comment by chalo2000** [comment]
8) Eatery tab button
